language: node_js
node_js:
  - '8'
after_success:
  - yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
  - yarn report-coverage
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
    secure: "kie3Nn/LTEwiiJl/y5V+XqENkvuOPtZBQjG9C6PrWJlblJZRESl6aJwqUZc3d4PunfkXZ1zHI0Rr2nqQ8g/dc8xG1bWqW2JhPnS0PL1NS30eD/VgHY1nC0FvVdzvo8af4W3UUlkpD8RkGn/0OdnS3QUHj+nEYxyq/Kt1CmKhzYFs5EkDjdBJTDHzNRpfwnioHGoR5Ccfc4VkX+AHCADZdsoR6gQSSw83EAmlGVu6AwXvV220TAbFWO/sJjAcDINub9ziCBB92F1ZikHo+nPKC4ibpSLpFuKfgLHzpRemqOfjj8fuFFf94YblwUOW7jeEqP75bzOfB3EVeI7S7kkCiZxxDDa8YnRxhsXabUA7Z3aKYdJ2aWBzkePiWDB94IyihMBxuNQh/JDk7B968MLwp7wv+Ghd/ABnYbbQYSPd3jfN+yP9geMZQZKL+gun45Kres3fvIkne7Rw9+R+dJlEOsqM0hr6AL6oti4UG9UeyEpM7j7Jt+XEi8gE1q84oLAuLgMIZyZRljEhK2BrYkC0oTv1N1bYDq0TB/pRT8AnCGUAbd3rOYOtGdsHdQSAYbJ4KoFg20bnSEHm3ZgLeGxFvNroZGzkUeAG3+HIc6nl9kKFHsL60LkqFhyXmVR6Usoi5KSofZcwXdPucs52JL3rdi3cF7e31TRPaRC7HBPzBsU="
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    branch: master
    repo: terascope/terafoundation
